language: php
php:
  - 5.5
  - 5.4
  - hhvm
install:
  - composer install --dev --prefer-source
notifications:
  irc: 
    channels:
      - "chat.freenode.org#wjzijderveld"
    on_success: change
    on_failure: change

